name: build

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

env:
  MESON_ARGS: >-
    --auto-features=enabled
    --fatal-meson-warnings

  MESON_ARGS_WIN: >-
    -Dwrap_mode=forcefallback

  MESON_ARGS_OTHER: >-
    -Dwrap_mode=nofallback

jobs:
  mingw:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["i686", "x86_64"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: subprojects/packagecache
          key: ${{ hashFiles('subprojects/*.wrap') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64 meson

      - name: Build
        run: |
          meson setup --cross-file=.ci/${{ matrix.arch }}-w64-mingw32.txt \
          ${{ env.MESON_ARGS }} ${{ env.MESON_ARGS_WIN }} builddir
          meson compile -C builddir
          ${{ matrix.arch }}-w64-mingw32-strip builddir/game*.dll

      - name: Set version
        id: setver
        run: |
          echo "revision=r$(git rev-list --count HEAD)" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-mingw-${{ steps.setver.outputs.revision }}
          path: builddir/game*.dll

  msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: ["x86", "x64"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: subprojects/packagecache
          key: ${{ hashFiles('subprojects/*.wrap') }}

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Install dependencies
        run: pip3 install --no-input meson ninja

      - name: Build
        run: |
          meson setup ${{ env.MESON_ARGS }} ${{ env.MESON_ARGS_WIN }} builddir
          meson compile -C builddir

      - name: Set version
        shell: bash
        id: setver
        run: |
          echo "revision=r$(git rev-list --count HEAD)" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-msvc-${{ steps.setver.outputs.revision }}
          path: |
            builddir/game*.dll
            builddir/game*.pdb

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson zlib1g-dev

      - name: Build
        run: |
          meson setup ${{ env.MESON_ARGS }} ${{ env.MESON_ARGS_OTHER }} builddir
          meson compile -C builddir
        env:
          CC: ${{ matrix.cc }}

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install meson

      - name: Build
        run: |
          meson setup ${{ env.MESON_ARGS }} ${{ env.MESON_ARGS_OTHER }} builddir
          meson compile -C builddir

  freebsd:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: cross-platform-actions/action@v0.24.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '14.0'
          run: |
            sudo pkg update
            sudo pkg install -y git meson
            meson setup ${{ env.MESON_ARGS }} ${{ env.MESON_ARGS_OTHER }} builddir
            meson compile -C builddir
